<?php
$santri = [
    ["nama"=>"Athar Izzy Fardhan Triyandanu","asal"=>"MA'HAD BINA TAHFIDZ INDONESIA","file"=>"1 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Athar Izzy Fardhan Triyandanu .pdf"],
    ["nama"=>"Aditya Kusuma Prananto","asal"=>"MA'HAD MUHIBBUL QUR'AN","file"=>"2 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Aditya Kusuma Prananto .pdf"],
    ["nama"=>"Zaid Abdurrahman","asal"=>"SMP TERPADU DAWAUL MUNAWAR / AL KHULAFA ARROSYIDUN","file"=>"3 Surat Keterangan Hasil Test dan Wawancara PPDB 2026-2027 Zaid Abdurrahman .pdf"],
    ["nama"=>"Ezra Mahiraqil Mufaza","asal"=>"PONDOK ALKHULFA AR ROSYIDUN","file"=>"4 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Ezra Mahiraqil Mufaza .pdf"],
    ["nama"=>"Bintang Khadafi Agung","asal"=>"TAHFIZHUL QUR'AN DAR EL HUDA MUARA BUNGO JAMBI","file"=>"5 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Bintang Khadafi Agung .pdf"],
    ["nama"=>"Ahmad Zaid","asal"=>"MAHAD ABU BAKR ASSHIDIQ","file"=>"6 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Ahmad Zaid .pdf"],
    ["nama"=>"Husain","asal"=>"MA'HAD TAHFIZ BUKIT MUMTAZ QUR'AN BOGOR","file"=>"7 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Husain .pdf"],
    ["nama"=>"Muhammad Zulfi Abdurrohim","asal"=>"MA'HAD TAHFIZHUL QUR'AN TARBIYAH SUNNAH","file"=>"8 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Zulfi Abdurrohim .pdf"],
    ["nama"=>"Abdul Baari","asal"=>"PONDOK PESANTREN AL IHSAN AL ISLAMY","file"=>"9 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Abdul Baari .pdf"],
    ["nama"=>"Muhammad Zein Muttaqiin","asal"=>"PONDOK PESANTREN JABAL RAHMAH","file"=>"10 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Zein Muttaqiin .pdf"],
    ["nama"=>"Juraij Assabani","asal"=>"IHYA ASSUNNAH TASIKMALAYA","file"=>"11 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Juraij Assabani .pdf"],
    ["nama"=>"Muhammad Kasyafani Elfarizi","asal"=>"PONPES MARKAZ HADITS BSD TANGERANG","file"=>"12 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Kasyafani Elfarizi .pdf"],
    ["nama"=>"Syamil Husni Muttaqin","asal"=>"MAHAD MUHIBBUL QURAN","file"=>"13 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Syamil Husni Muttaqin .pdf"],
    ["nama"=>"Faqih","asal"=>"MA'HAD TAHFIZHUL QUR'AN TARBIYAH SUNNAH","file"=>"14 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Faqih .pdf"],
    ["nama"=>"Rafif Ilham Praditya","asal"=>"PONDOK PESANTREN ABDURRAHMAN BIN AUF SALAFIYAH TINGKAT WUSTHA","file"=>"15 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Rafif Ilham Praditya .pdf"],
    ["nama"=>"Faiza Rizky Muhammad","asal"=>"PKBM KAWALI / RTQ KAWALI","file"=>"16 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Faiza Rizky Muhammad .pdf"],
    ["nama"=>"Isa Abdurohman","asal"=>"PKBM WINA","file"=>"17 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Isa Abdurohman .pdf"],
    ["nama"=>"Muhammad Ihsan Nasrullah","asal"=>"PESANTREN AZ-ZAHRA PACET","file"=>"18 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Ihsan Nasrullah .pdf"],
    ["nama"=>"Muhammad Taqi Al Mufadhdhol","asal"=>"PONDOK PESANTREN MUSLIM ROBBANI","file"=>"19 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Taqi Al Mufadhdhol .pdf"],
    ["nama"=>"Muammar At-Tirmidzi Arjuna Askar","asal"=>"PONPES IMAM SYAFI'I","file"=>"20 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muammar At-Tirmidzi Arjuna Askar .pdf"],
    ["nama"=>"Nizzam Mulkil Akbar El Fayyeed Habibi","asal"=>"MA'HAD AL KHULAFA AR RASYIDUN","file"=>"21 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Nizzam Mulkil Akbar El Fayyeed Habibi .pdf"],
    ["nama"=>"Ziad Abdullah","asal"=>"SMP TERPADU DAWAUL MUNAWAR / AL KHULAFA ARROSYIDUN","file"=>"22 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Ziad Abdullah .pdf"],
    ["nama"=>"Muhammad Hanif","asal"=>"PONDOK PESANTREN TAHFIZH BUKIT MUMTAZ QUR'AN","file"=>"23 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Hanif .pdf"],
    ["nama"=>"Hibban Ibnu Yaya","asal"=>"MA'HAD IHYA AS-SUNNAH","file"=>"24 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Hibban Ibnu Yaya .pdf"],
    ["nama"=>"Muhammad Faiz Al-Hafidz","asal"=>"PONDOK TAHFIDZ QURAN ADDAWA KARAWANG","file"=>"25 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Faiz Al-Hafidz .pdf"],
    ["nama"=>"Daviandra Adil Fadhlurrahman","asal"=>"MA'HAD SABILURRASYAD BANDUNG","file"=>"26 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Daviandra Adil Fadhlurrahman .pdf"],
    ["nama"=>"Yusuf Nur Fadilah","asal"=>"SMPIT GEMA INSAN CENDEKIA / PTQ AD-DAWA","file"=>"27 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Yusuf Nur Fadilah .pdf"],
    ["nama"=>"Muh. Dzakwan Syawal","asal"=>"SMP IT DAARUL HAFFADZ GOWA","file"=>"28 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muh. Dzakwan Syawal .pdf"],
    ["nama"=>"Muhammad Fathir Arafah","asal"=>"FATHUL BAARI ISLAMIC SCHOOL","file"=>"29 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Fathir Arafah .pdf"],
    ["nama"=>"Muhamad Ubaidillah","asal"=>"SMP NEGRI 3 CILEUNGSI","file"=>"30 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhamad Ubaidillah .pdf"],
    ["nama"=>"Malik Algifari","asal"=>"MTSS PERSIS 324 AL AQSHA","file"=>"31 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Malik Algifari .pdf"],
    ["nama"=>"Isa Abdullah","asal"=>"IHYA ASSUNNAH TASIKMALAYA","file"=>"32 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Isa Abdullah .pdf"],
    ["nama"=>"Nazeef Marvyn Revano","asal"=>"MA'HAD BINA MADANI KUNINGAN","file"=>"33 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Nazeef Marvyn Revano .pdf"],
    ["nama"=>"Muhammad Khoirunnizam","asal"=>"MA'HAD BINA TAHFIDZ INDONESIA","file"=>"34 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Khoirunnizam .pdf"],
    ["nama"=>"Radithya Haidar Fakhrizal","asal"=>"PONPES SABILUNNAJAH BANDUNG","file"=>"35 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Radithya Haidar Fakhrizal .pdf"],
    ["nama"=>"Fadhilah Rafi Nakhlah","asal"=>"MA'HAD IMAM SYAFI'I CABANGBUNGIN","file"=>"36 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Fadhilah Rafi Nakhlah .pdf"],
    ["nama"=>"Ubay Hafsh Alfaruq","asal"=>"PESANTREN AL LULU WAL MARJAN MEGELANG","file"=>"37 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Ubay Hafsh Alfaruq .pdf"],
    ["nama"=>"Bagus","asal"=>"-","file"=>"38 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Bagus .pdf"],
    ["nama"=>"Mohamad Fardan","asal"=>"AL-KHULAFA AR-RASYIDUN","file"=>"39 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Mohamad Fardan .pdf"],
    ["nama"=>"Faiz Kahla Akmal","asal"=>"MA'HAD IMAM SYAFII BANTARSARI","file"=>"40 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Faiz Kahla Akmal .pdf"],
    ["nama"=>"Muhammad Haidar Nur Waliyyun","asal"=>"PONDOK PESANTREN DAARUL HUFFAZH CIREBON","file"=>"41 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Haidar Nur Waliyyun .pdf"],
    ["nama"=>"Zainu Musa","asal"=>"SMP BHINEKA KARYA BOYOLALI / PPTQ NURUL ISLAM BOYOLALI","file"=>"42 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Zainu Musa .pdf"],
    ["nama"=>"Sayid Maulana Ishaq","asal"=>"MA'HAD TAHFIDZ AL QUR'AN IMAM SYAFI'I","file"=>"43 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Sayid Maulana Ishaq .pdf"],
    ["nama"=>"Muhammad","asal"=>"PPS ANSHARUSSUNNAH POLEWALI MANDAR","file"=>"44 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad .pdf"],
    ["nama"=>"Abdulbarr","asal"=>"AL-AQSHO JONGGOL","file"=>"45 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Abdulbarr .pdf"],
    ["nama"=>"M. Syaban Alhad Amrullah","asal"=>"MI RAUDLATUL MUTA'ALLIMIN","file"=>"46 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 M. Syaban Alhad Amrullah .pdf"],
    ["nama"=>"Muhammad Rifal Arrafqi","asal"=>"CAHAYA ILMU","file"=>"47 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Rifal Arrafqi .pdf"],
    ["nama"=>"Muhammad Imam Ali Al Fadhil","asal"=>"MA'HAD DARR AL-SHUFFAH","file"=>"48 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Imam Ali Al Fadhil .pdf"],
    ["nama"=>"Muhammad Rasyid Ridho","asal"=>"SMP MUHAMMADIYAH 4 KOTA DEPOK","file"=>"49 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Rasyid Ridho .pdf"],
    ["nama"=>"Miftah Fauzi","asal"=>"DAARUS SUNNAH WANGON","file"=>"50 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Miftah Fauzi .pdf"],
    ["nama"=>"Faiz Abbasy Abdad","asal"=>"-","file"=>"51 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Faiz Abbasy Abdad .pdf"],
    ["nama"=>"Muhammad Akbar","asal"=>"PONDOK PESANTREN JABAL RAHMAH","file"=>"52 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Muhammad Akbar .pdf"],
    ["nama"=>"Althaf Fauzi Rahman","asal"=>"RUMAH BELAJAR IMAM MALIK","file"=>"53 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Althaf Fauzi Rahman .pdf"],
    ["nama"=>"Abdulloh Alkarim","asal"=>"PKBM ABU BAKAR ASH-SHIDDIQ","file"=>"54 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Abdulloh Alkarim .pdf"],
    ["nama"=>"Hanif Abdul Wahhab","asal"=>"SMPIT IHYA AS-SUNNAH TASIKMALAYA","file"=>"55 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Hanif Abdul Wahhab .pdf"],
    ["nama"=>"Rayan Adam","asal"=>"MA'HAD TAHFIDZ AL QUR'AN IMAM ASY SYAFI'I","file"=>"56 Surat Keterangan Hasil Test dan Wawancara PPDB 2026_2027 Rayan Adam .pdf"]
];
